baseurl = "https://download.spideroak.com"
defaultContentLanguage = "en"
languageCode = "en"
theme = "hugo-three"
enableRobotsTXT = true
metaDataFormat = "yaml"
title = "SpiderOak Downloads"

# [params]
#   mainSections = ["share", "semaphor", "one", "groups", "notes"]

[blackfriday]
hrefTargetBlank = false
latexDashes = true
plainIDAnchors = true

[menu]
    [[menu.main]]
    identifier = "share"
    name = "Share Menu Item"
    url = "/share/"
    weight = 1
    [[menu.main]]
    identifier = "semaphor"
    name = "Semaphor Messaging"
    url = "/semaphor/"
    weight = 2
    [[menu.main]]
    identifier = "one"
    name = "One Backup"
    url = "/one/"
    weight = 3
    [[menu.main]]
    identifier = "groups"
    name = "Groups Backup"
    url = "/groups/"
    weight = 4
    [[menu.main]]
    identifier = "releases"
    name = "Release Notes"
    url = "/releases/"
    weight = 5
    [[menu.main]]
    identifier = "support"
    name = "SpiderOak Support"
    url = "https://spideroak.support/hc/en-us/"
    weight = 6


	# [[menu.releases]]
	# 	identifier = "all"
	# 	name = "all"
	# 	title = "all"
	# 	url = "/"
	# 	weight = 1

	# [[menu.releases]]
	# 	identifier = "share"
	# 	name = "share"
	# 	title = "Share"
	# 	url = "#share"
	# 	weight = 2

	# [[menu.releases]]
	# 	identifier = "semaphor"
	# 	name = "semaphor"
	# 	title = "semaphor"
	# 	url = "#semaphor"
	# 	weight = 3

	# [[menu.releases]]
	# 	identifier = "one"
	# 	name = "one"
	# 	title = "one"
	# 	url = "#one"
	# 	weight = 4

  #   [[menu.releases]]
	# 	identifier = "groups"
	# 	name = "groups"
	# 	title = "groups"
	# 	url = "#groups"
	# 	weight = 5

# [outputFormats.Redirects]
# baseName = "redirects"
# isPlainText = true
# mediatype = "application/json"
# notAlternative = true
# [outputs]
# home = ["HTML", "RSS", "OpenSearch", "Algolia", "Redirects"]

[social]
email = "https://spideroak.support/hc/en-us/requests/new"
twitter = "spideroak"
facebook = "SpiderOak"
vimeo = "spideroak"

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"
note = "notes"
product = "products"
